### ISSUE TITLE
Center the due date coloumn

### ISSUE THREAD

**Issue by Yuvraj0157** [Yuvraj0157/simpleTodoApp#1]
![image](https://github.com/user-attachments/assets/11055e5a-a885-4ceb-8af8-f47423b03f7f)

As you can see currently the due date field is adjacent to the todo task title. Dividing each todo rows in three columns for title,due date,button will be great.

**Comment by azhar-sayyad** [comment]
Hi, can you please assign this issue to me? I'd love to work on it.

**Comment by Yuvraj0157** [comment]
sure

**Comment by azhar-sayyad** [comment]
Hi @Yuvraj0157, I hope you're doing well! Could you please provide guidance on setting up the project? I'd appreciate any steps or documentation you could share. Thank you!

**Comment by Yuvraj0157** [comment]
Hi @Azhar221, I have updated the README.md to help you with project setup locally on your machine.

**Comment by devalcodes** [comment]
@Yuvraj0157 Please review the PR
