### ISSUE TITLE
 Add a login button in the "Forgot Password" section

### ISSUE THREAD

**Issue by naikmubashir** [Yuvraj0157/simpleTodoApp#2]
### Description
When I clicked on the "Forgot Password" link, there was no way to navigate back to the login page. This could cause inconvenience to users who may want to return to the login page after initiating the password reset process.

### Expected Behavior
There should be a "Login" button or a link in the "Forgot Password" section to allow users to easily return to the login page.

### Proposed Solution
Add the "Login" button  in the "Forgot Password" component that redirects users back to the login page.

### Steps to Reproduce
1. Go to the login page.
2. Click on "Forgot Password".
3. Observe the lack of a way to return to the login page.

**Comment by Yuvraj0157** [comment]
Users can go back to the home page by clicking the app logo.
