### ISSUE TITLE
Show only todos button if user is logged in else show login and register button.

### ISSUE THREAD

**Issue by Yuvraj0157** [Yuvraj0157/simpleTodoApp#3]
![image](https://github.com/user-attachments/assets/cd8c1608-8ba1-4687-a0ab-31147555e535)

The authentication system is based on jwt. Users get the jwt token upon login which the user will use for subsequent access to todos without requiring to login again( for 5 days - cookie/jwt expiry time).

Now, It would be a great UX if the user doesn't see the login/register button on the homepage if he/she already has a valid cookie.

So, we can store an additional field in the response cookie along with jwt something like, isLoggedIn = true/false which we can use to render the buttons dynamically in EJS templates.

**Comment by Zish303** [comment]
@Yuvraj0157 I would like to work on this feature. Please assign this to me.

**Comment by Yuvraj0157** [comment]
Sure
